version: '2'

services:
    web:
      image: nginx:latest
      ports:
        - "8080:80"
      volumes:
        - ./webroot:/webroot
        # - ./ssl/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
        # - ./ssl/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        # - ./nginx/nginx-ssl.conf:/etc/nginx/conf.d/default-ssl.conf
        - ./logs:/var/log/nginx
      links:
        - php
    php:
      build:
        context: ./php
      ports:
        - 9000:9000
      volumes:
        - ./webroot:/webroot
        - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      environment:
        - DB_PORT=3306
        - DB_HOST=mysql
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    mysql:
      image: mysql:latest
      ports:
        - "3350:3306"
      links:
        - php
      environment: 
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      volumes:
        - ./dbdata:/var/lib/mysql
        - ./dbstructure/dbdump.sql:/docker-entrypoint-initdb.d/dbdump.sql
